1. Introducción: Esta página establece los "términos y condiciones" bajo los cuales usted puede utilizar solicituddeempleo.com.mx. Por favor lea esta página cuidadosamente. Si no acepta los términos y condiciones establecidos aquí, no utilice este sitio de Internet ni este servicio.
2. Aceptación de Términos: Al utilizar este sitio de Internet, usted acepta obligarse a éstos términos y condiciones. Los términos y condiciones pueden ser actualizados por solicituddeempleo.com.mx  en cualquier momento y sin previo aviso por lo que debe visitar ésta página periódicamente para consultar la versión más reciente de los términos y condiciones. Los términos "usted" y "usuario" según se utilizan aquí hacen referencia a todas las personas y/o entidades que acceden a este sitio de Internet por cualquier razón.
3. Acuerdo Obligatorio: Estos términos (pueden ser cambiados periódicamente por solicituddeempleo.com.mx) forman un acuerdo obligatorio entre usted y solicituddeempleo.com.mx. El acceso y uso de solicituddeempleo.com.mx indica su aceptación de estos términos. Asimismo, usted acuerda utilizar solicituddeempleo.com.mx a su propio riesgo. Tratándose de contratación electrónica de servicios, ésta se perfeccionará desde que se reciba la aceptación de la propuesta o las condiciones con que ésta fuere modificada.
4. Descripción del Servicio: Los servicios que se prestan a través del sitio solicituddeempleo.com.mx operado por MY SECRETS INCORPORATED, S.A. DE C.V. (en adelante SOLICITUD DE EMPLEO) quién es su propietario, son exclusivamente de proporcionando una plataforma para que empleadores ajenos a SOLICITUD DE EMPLEO publiquen ofertas de trabajo y vacantes de empleo, y a su vez los candidatos publiquen sus currículums en el sistema. De igual forma, SOLICITUD DE EMPLEO es un intermediario para la oferta de servicios educativos y de capacitación prestados por terceros, con los cuales SOLICITUD DE EMPLEO mantiene convenios de colaboración. Queda establecido que usted entiende y acepta que el servicio puede incluir ciertas comunicaciones de SOLICITUD DE EMPLEO, como mensajes administrativos y anuncios de servicio, éstas comunicaciones son consideradas como parte del servicio de SOLICITUD DE EMPLEO y usted no puede excluir la recepción de dichas comunicaciones. 
5. Definiciones: Las siguientes son definiciones de términos usadas o aplicadas a la información aquí contenida:
•    Recolección de datos del Candidato": significa el proceso de obtener información (personal y/o de empleo) sobre un candidato utilizando información falsa, ficticia, engañosa que atraigan a un candidato con el fin de obtener información personal o de empleo que el ó ella no divulgarían si la intención de dicha oferta fuera previamente conocida por el candidato.
•    Diseño": Incluye las combinaciones de color y el diseño de la página WEB.
•    Empleador": Significa la persona o entidad que ingresa al sitio para colocar una oferta de trabajo o por cualquier razón relacionada al propósito de buscar candidatos.
•    Gráficas": Incluye todos los logotipos, botones y otros elementos gráficos en el Sitio Web, con la excepción de banners de publicidad.
•    Sitio solicituddeempleo.com.mx:" incluye www.solicituddeempleo.com.mx en su totalidad y sus sitios relacionados que opera y son propiedad de MY SECRETS INCORPORATED, S.A. DE C.V. Incluyendo su contenido, texto, gráficas, diseño, programación y servicios aplicables en el contexto. 
•    Candidato": significa un usuario que accede al Sitio Web para buscar un empleo y que no es un empleador.
•    Materiales": Se refiere a cualquier publicación hecha en el Sitio Web. La herramienta de servicio “ATS" está incluida bajo los presentes términos.
•    Programación": Incluye códigos de ambos lados del cliente (HTML, JavaScript, etc.) y el código del servidor (Páginas activas del servidor, VBScript, Bases de Datos, etc.) usadas en el Sitio Web.
•    Servicios": Significa cualquier servicio proporcionado en Internet por MY SECRETS INCORPORATED, S.A. DE C.V., sus agentes o miembros, o por solicituddeempleo.com.mx
•    Texto": Incluye todo el texto en cada página del Sitio Web, ya sea editorial, de navegación en la página ó instruccional.
•    Terceras partes": Incluye cualquier persona o entidad no especificada directamente en este acuerdo.
•    Usuario": Se refiere a cualquier individuo o entidad que utilice cualquier aspecto del Sitio Web.
•    Usted": significa la persona (o la entidad representada por la que se está actuando) que está aceptando éstos términos y condiciones.
6. Reglas de Uso General del Sitio solicituddeempleo.com.mx: El portal está previsto para individuos que buscan trabajo y para empleadores o reclutadores que buscan candidatos para ofrecerles empleo. Usted debe usar este Sitio Web con intenciones legítimas y de acuerdo a las indicaciones de uso dictadas por MY SECRETS INCORPORATED, S.A. DE C.V., SOLICITUD DE EMPLEO es la única entidad que interpretará el uso aceptable del Sitio Web.
7. Licencia de uso para empresas: SOLICITUD DE EMPLEO otorga un acuerdo de responsabilidad limitada, terminable y con derechos de no exclusividad para accesar y usar el Sitio Web para el uso interno de la empresa en la búsqueda de candidatos para ofrecerles empleo. Esto le autoriza a usted a ver y bajar una copia del material del Sitio Web solamente para su uso personal con el propósito de buscar y reclutar candidatos. SOLICITUD DE EMPLEO se reserva el derecho de suspender sus claves de acceso o dar por terminado su contrato si se determina que existe un incumplimiento de cualquiera de estos términos y condiciones. Usted no podrá comercializar ni revender en forma alguna los servicios o porciones de éstos. 
SOLICITUD DE EMPLEO otorga a la empresa contratante una clave de usuario administrador, cuyo titular será responsable de la existencia y veracidad de la información de las subcuentas generadas, así como por el uso que dichas claves den al servicio contratado por la empresa. 
De conformidad con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares, SOLICITUD DE EMPLEO es responsable transferente y el cliente se convierte en responsable receptor, por lo que en cumplimiento con las disposiciones de la materia, el cliente al contratar el servicio, se obliga a:
•    Mantener la confidencialidad de los datos personales únicamente para efectos de reclutamiento y selección de personal y con ningún otro propósito.
•    No transferir a ningún tercero, datos personales que recibe en su calidad de responsable receptor, salvo por lo dispuesto en el artículo 70 de reglamento de LFPDPPP.
•    Garantizar que solo sus empleados tendrán acceso a los datos transferidos y que ninguno de ellos dará un tratamiento distinto al de reclutamiento y selección de personal.
SOLICITUD DE EMPLEO se deslinda de cualquier responsabilidad presente o futura, que surja del uso no convenido de los datos personales que le han sido transferidos a los clientes.
8. Licencia de uso para Candidatos: SOLICITUD DE EMPLEO otorga un acuerdo de responsabilidad limitada, terminable y con derechos de no exclusividad para accesar y usar el Sitio Web para el uso personal en la búsqueda de oportunidades de empleo para usted mismo. Esto le autoriza a usted a ver y a bajar una copia del material del Sitio Web solamente para su uso personal y no para uso comercial con fines de lucro. Su uso del Sitio Web es un privilegio. SOLICITUD DE EMPLEO se reserva el derecho de suspender o terminar este privilegio por cualquier razón y en cualquier momento. 
9. Otras Reglas Particulares de Uso del Sitio Web: Usted representa, garantiza y acepta que usted no usará (o planeará, motivará o ayudara a otros a usar) el Sitio Web para cualquier otro propósito o que en cualquier manera esté prohibido por los términos aquí mencionados o los que sean aplicables por ley. Es su responsabilidad asegurar que usted use el Sitio Web de acuerdo a los términos aquí especificados.
10. Reglas de Publicación. Conducta y Seguridad: Usted acepta cumplir con las reglas de SOLICITUD DE EMPLEO para la Publicación de Vacantes, de Conducta y de Seguridad en este sitio Web. Usuarios que violen dichas reglas tendrán el uso y el acceso del sitio suspendido o cancelado a discreción exclusiva de SOLICITUD DE EMPLEO. 
SOLICITUD DE EMPLEO se reserva el derecho de cambiar estas reglas. Las reglas de Conducta, Publicación y Seguridad son como se describe a continuación:
10.1 General: La información de contacto de SOLICITUD DE EMPLEO está listada en el Sitio Web. SOLICITUD DE EMPLEO y sus agentes asociados no asume responsabilidad de que el contenido sea apropiado o sea bajado fuera de la República Mexicana. El acceso al contenido del sitio de Internet puede no ser legal para ciertas personas o en ciertos países. Si usted tiene acceso al contenido del sitio de Internet desde fuera de la República Mexicana, lo hace a su propio riesgo y es responsable por el cumplimiento de las leyes dentro de su jurisdicción. El Usuario se compromete a utilizar el Sitio Web y los Servicios de conformidad con la ley, estas Condiciones Generales, las Condiciones Particulares aplicables, así como con la moral y buenas costumbres generalmente aceptadas y el orden público. SOLICITUD DE EMPLEO excluye cualquier responsabilidad por los daños y perjuicios de toda naturaleza que puedan deberse a los servicios prestados por terceros a través del Sitio Web, y en particular, aunque no de modo exclusivo por los daños y perjuicios que puedan deberse a el incumplimiento de la ley, la moral y las buenas costumbres generalmente aceptadas o de orden público como consecuencia de la prestación de servicios por terceros a través del Sitio Web; la infracción de los derechos de propiedad intelectual e industrial, de los secretos empresariales, de compromisos contractuales de cualquier clase, de los derechos al honor, a la intimidad personal y familiar y a la imagen de las personas, de los derechos de propiedad y de toda otra naturaleza pertenecientes a un tercero como consecuencia de la prestación de servicios por terceros a través del portal; la realización de actos de competencia desleal y publicidad ilícita como consecuencia de la prestación de servicios por terceros a través del portal, la falta de veracidad, exactitud, exhaustividad, pertinencia y/o actualidad de los contenidos transmitidos, difundidos, almacenados, recibidos, obtenidos, puestos a disposición o accesibles mediante los servicios prestados por terceros a través del portal; el incumplimiento, retraso en el cumplimiento, cumplimiento defectuosos o terminación por cualquier causa de las obligaciones contraídas por terceros y contratos realizados con terceros en relación o con motivo de la prestación de servicios a través del portal; los vicios y defectos de toda clase de los servicios prestados a través del portal. Usted no debe asignar o transferir sus obligaciones bajo estos términos, estas condiciones constituyen todo el contrato entre usted y la empresa con respecto al uso del sitio de Internet. SOLICITUD DE EMPLEO se reserva el derecho a denegar o retirar el acceso al Portal y/o a los Servicios, en cualquier momento y sin necesidad de preaviso, a aquellos usuarios que incumplan estas Condiciones Generales o las Condiciones Particulares que resulten de la aplicación.
10.2 Reglas de Publicación:
A. Su (s) Material (es) no deben contener:
•    Hipervínculos, hiperenlace, ligas o direcciones URL’s que no estén previamente contratados e incluidos en nuestro “Paquete de Direccionamiento" en tal caso, los enlaces deben ir dirigidos exclusivamente al sitio con el dominio de la página principal (Home Page) de usted, la empresa contratante, o cualquier variante de ese dominio, tal como son directorios y subdirectorios.
•    No debe publicar simultáneamente la misma vacante.
•    Publicación de diversos perfiles en la misma vacante.
•    Material que requiera derechos de autor (a menos que se tengan los derechos y/o el permiso del autor para su publicación);
•    Información confidencial o secretos corporativos (a menos que se tengan los derechos y/o el permiso del autor para su publicación);
•    Material que infrinja cualquier otro derecho de autor o viole la privacidad o los derechos de publicación de otros;
•    Cualquier material que sea sexualmente explícito, obsceno, difamatorio, amenazante, acosador, abusivo, dañino; o
•    Cualquier cosa que sea embarazosa u ofensiva para otra persona o entidad;
•    Solicitud de servicios personales;
•    Trabajos que sean pagados solamente por comisión;
•    Trabajos que no paguen por lo menos el salario mínimo diario;
•    Trabajos que requieran que el candidato, ó empleado, haga una inversión de capital;
•    Trabajos que requieran que el candidato, ó empleado, vaya a un entrenamiento no pagado para ser contratado;
•    Ningún otro lenguaje que no sea el Español o el Inglés.
•    Datos personales sensibles.
B. Usted NO deberá usar su (s) Material (es) para:
•    Representar a otra persona, viva o muerta;
•    Publicar información falsa, imprecisa o engañosa;
•    Anuncios Publicitarios o pedidos de negocios (incluyendo, posiciones para empresas de tipo multinivel, franquicias, FOREX, clubes de membresías, distribución de productos, o cualquier otra que requiera inversión monetaria por parte del usuario);
•    Publicar cadenas de cartas ó esquemas piramidales;
•    Publicar opiniones o noticias, anuncios comerciales, promoción de cursos y/o de productos; o
•    Recolectar información masiva de candidatos;
C. Su(s) material(es) deben contener suficientes detalles para transmitir claramente al usuario la naturaleza y requerimientos de la oportunidad de trabajo, o las calificaciones como un candidato para el empleo (datos biográficos completos, datos propios verídicos).
D. Materiales de terceros que requieran una cuota o restrinjan de alguna forma el acceso a la información del currículo están prohibidos.
E. SOLICITUD DE EMPLEO mantendrá un cuidado razonable para asegurar la calidad de su Sitio Web, sin embargo no es su obligación monitorear los materiales publicados. SOLICITUD DE EMPLEO podrá monitorear los materiales publicados en forma aleatoria.
F. Es responsabilidad directa de las empresas que la publicación de ofertas a través de SOLICITUD DE EMPLEO esté apegada a la ley de acuerdo a la jurisdicción del país al que corresponde, dependiendo de la localidad en la cual se encuentra la oferta de empleo. En particular es de suma importancia cumplir con las obligaciones antidiscriminatorias que establece la legislación y no restringir el acceso al empleo en virtud de origen étnico o nacional, el género, la edad, talla pequeña, las discapacidades, la condición social, las condiciones de salud, la religión, las opiniones, las preferencias, el estado civil o cualquier otra que atente contra la dignidad humana y tenga por objeto anular o menoscabar los derechos y libertades de las personas, lo que podría constituir una conducta que tiene el efecto de anular el ejercicio de sus derechos y la igualdad real de oportunidades con respecto al resto de los y las demás aspirantes a ocupar un empleo.
Los Materiales que sean encontrados y violen las Reglas de Publicación mencionadas anteriormente serán removidos a criterio exclusivo de SOLICITUD DE EMPLEO
10.3 Reglas de Conducta:
•    Usted no puede responder a publicaciones a nombre de otros usuarios de ninguna manera y para ningún otro propósito que el esperado (ejemplo, para aplicar al trabajo o para iniciar una discusión con referencia al trabajo). Comunicaciones solicitando el negocio del empleador están prohibidas.
•    Usted no puede enviar correos electrónicos comerciales a los usuarios.
•    Reporte publicaciones o conducta inapropiada a: ayuda@solicituddeempleo.com.mx
•    Usted no puede borrar o revisar ningún material publicado por ninguna otra persona o entidad.
•    Si en cualquier momento durante el término del presente contrato SOLICITUD DE EMPLEO l se entera que usted lo ha engañado en cuanto a su práctica de negocios y/o servicios, y/o ha comprado servicios que no representan precisamente su negocio, SOLICITUD DE EMPLEO se reserva el derecho de terminar el presente contrato y su uso de privilegios inmediatamente sin previa notificación.
•    SOLICITUD DE EMPLEO no tiene obligación de monitorear la conducta de sus usuarios pero se compromete a investigar y responder cuando se reporten violaciones a los términos aquí mencionados.
10.4 Reglas de Seguridad:
A. Los usuarios tienen prohibido violar o atentar contra la seguridad del Sitio Web, incluyendo, sin limitación:
•    Accesar datos que no sean previstos para ese usuario o ingresar a un servidor o cuenta en la cual el usuario no esté autorizado para accesar. Si usted tiene una contraseña que le permita acceso a un área no pública de este sitio de Internet, no podrá divulgar o compartir su contraseña con terceros o utilizar su contraseña para cualquier fin no autorizado. 
•    Atentar, explorar o probar la vulnerabilidad del sistema o de la red o tratar de traspasar la seguridad o las medidas de autenticación sin autorización previa;
•    Atentar e interferir con el servicio de cualquier usuario, servidor o red, (host, network) a través del envío de un virus al Sitio Web, u otros actos como sobrecarga (overloading, flooding);
•    Enviar e-mails no solicitados, incluyendo promociones y/o publicidad de productos o servicios;
B. Violación a estas Reglas de Seguridad puede resultar en responsabilidad civil o criminal. SOLICITUD DE EMPLEO investigará los casos que puedan presentar dichas violaciones e implicará, y cooperará con las respectivas autoridades en el proceso jurídico de los usuarios que estén implicados en esas violaciones.
11. Derechos de Propiedad Intelectual: El Sitio Web y todos sus derechos, título e intereses del Sitio Web son propiedad única de MY SECRETS INCORPORATED, S.A. DE C.V., y se encuentran protegidos por la leyes mexicanas de derechos de autor y de los tratados internacionales. A excepción de las licencias de uso limitado expresamente otorgadas a usted en estos términos, SOLICITUD DE EMPLEO se reserva para el mismo y sus licenciatarios todos los derechos, títulos e intereses, sin límite de propiedad en lo aquí mencionado usted no puede reproducir, modificar, mostrar, vender o distribuir el contenido, o usarlo en cualquier otra forma para uso público o comercial. Esto incluye copiar o adaptar código HTML usado para generar páginas Web en el Sitio Web solicituddeempleo.com.mx. El logotipo de SOLICITUD DE EMPLEO y otros nombres y logotipos son marcas de servicio y marcas registradas de MY SECRETS INCORPORATED, S.A. DE C.V., y todos los productos y nombres de servicio, diseño de marcas y slogans publicitarios son marcas registradas de SOLICITUD DE EMPLEO.
12. Limitación de responsabilidad de SOLICITUD DE EMPLEO: SOLICITUD DE EMPLEO no asume ninguna responsabilidad por materiales publicados en el Sitio Web por los usuarios y no tiene responsabilidad por sus actividades, omisiones o conducta de los usuarios. 
Por ningún motivo los servicios prestados por SOLICITUD DE EMPLEO deben entenderse como servicios conocidos como outsourcing, manejo de nóminas, ni ningún servicio similar, por lo que SOLICITUD DE EMPLEO no puede ser considerado por ningún medio o forma como patrón sustituto en términos de la Ley Federal del Trabajo vigente en los Estados Unidos Mexicanos. Las ofertas de trabajo publicadas en el sitio solicituddeempleo.com.mx  y las relaciones individuales de trabajo que puedan derivar de ellas, son exclusiva responsabilidad de la persona que lleva a cabo su publicación, motivo por el cual, cualquier persona que publique una oferta de trabajo, libera desde este momento y en el futuro a SOLICITUD DE EMPLEO de cualquier responsabilidad derivada de la Ley Federal del Trabajo vigente en los Estados Unidos Mexicanos.
Asimismo, SOLICITUD DE EMPLEO no es responsable por los servicios educativos y de capacitación prestados por terceros con los que SOLICITUD DE EMPLEO tiene convenios de colaboración, por lo que cualquier reclamación deberá ser realizada de manera directa con el proveedor del servicio educativo.
SOLICITUD DE EMPLEO no será responsable por las fallas presentadas en la realización de pagos mediante plataformas de terceros, por lo que toda aclaración referente a este tema deberá ser canalizada de manera directa a la empresa encargada de llevar a cabo dicha transacción. 
Adicionalmente deberá considerarse que según el medio de pago utilizado para la contratación de servicios, éstos podrán no estar disponibles sino hasta 36 horas hábiles posteriores a la realización del pago correspondiente. 
13. Exclusión de Anexos por SOLICITUD DE EMPLEO: Nada en el Sitio Web debe ser considerado un anexo, representación o garantías con respecto a cualquier usuario o un tercero, ya sea en relación al Sitio Web, a sus productos, servicios, contrataciones, experiencia, empleo, prácticas de reclutamiento u otras.
14. Exclusión de Garantías y de responsabilidad: SOLICITUD DE EMPLEO no es una agencia de empleos ni una firma de reclutamiento, y no tiene ninguna representación ni garantiza la efectividad o el tiempo en la obtención de empleo para los usuarios. SOLICITUD DE EMPLEO  no garantizan los materiales publicados en este sitio por usuarios que resulten candidatos contratados o por puestos por cubrir y no es responsable de ninguna decisión sobre un empleo, por cualquier razón hecho por cualquier usuario.
15. Exclusión de errores y precisión de los materiales publicados en el Sitio Web: SOLICITUD DE EMPLEO no garantiza la veracidad, exactitud, vigencia o confiabilidad de ninguno de los materiales publicados por los usuarios, o por cualquier otra forma de comunicación que sea comprometida por los usuarios. Los materiales pueden contener inexactitudes o errores tipográficos. Usted acepta que cualquier consecuencia en materiales publicados por los usuarios, o en cualquier otra forma de comunicación con los usuarios, será a su propio riesgo. Adicionalmente SOLICITUD DE EMPLEO no garantiza el contenido del Sitio Web incluyendo responsabilidad limitada hacía, ligas que no funcionen, inexactitudes o errores tipográficos. 
16. EXCLUSIÓN DE GARANTÍAS: El sitio y todo su contenido es proveído sin garantías de ninguna clase, expresas o implícitas. La empresa y sus agentes asociados, hasta donde lo permita la ley, limitan la responsabilidad de todas las garantías, incluyendo pero no limitando la garantía de comercialización, idoneidad para un propósito específico y no infracción. La empresa y sus agentes asociados  no ofrecen garantías acerca de la precisión, confiabilidad, integridad u oportunidad del contenido del sitio de internet, servicios, software, texto, gráficas y vínculos. SOLICITUD DE EMPLEO y sus agentes asociados  no garantiza que el sitio va a operar libre de errores o que el sitio y sus servidores están libre de virus informáticos u otros mecanismos dañinos. Si su uso del sitio web resulta directa o indirectamente en la necesidad de remplazar equipos o datos o realizar servicios, SOLICITUD DE EMPLEO y sus agentes asociados no son responsables por los costos asociados con dichos reemplazos y/o servicios.
17. Terminación: SOLICITUD DE EMPLEO y sus agentes asociados se reservan el derecho, a su entera discreción, a perseguir todos los remedios legales, incluyendo, sin limitación, la eliminación de sus publicaciones en este Sitio Web, la terminación inmediata de claves de acceso a este Sitio Web y/o cualesquier otros servicios que le brinde la empresa y sus agentes asociados, debido a cualquier incumplimiento suyo a estos términos y condiciones de uso o si la empresa es incapaz de verificar o autentificar cualquier información que usted presente al sitio de Internet u otros registros; En caso de cancelación del servicio por estas causas SOLICITUD DE EMPLEO ni sus agentes asociados harán ningún reembolso de cantidades pagadas por la terminación del servicio.
18. Ligas a otros sitios: SOLICITUD DE EMPLEO y sus agentes asociados contienen ligas o hipervínculos a Sitios de terceros. Estás ligas son proporcionadas para conveniencia de ustedes y los contenidos no son avalados por SOLICITUD DE EMPLEO. SOLICITUD DE EMPLEO no es responsable por el contenido de esos sitios ni por la exactitud de sus materiales. Si usted decide accesar a esos sitios es su responsabilidad.
19. Enmiendas a este acuerdo y Cambios al Sitio Web: SOLICITUD DE EMPLEO podrá revisar estos términos en cualquier momento y actualizar su contenido. Cualquier uso del Sitio Web se considerará como aceptación de usted de los términos aquí mostrados. Si en cualquier momento usted encuentra los términos inaceptables, usted no deberá usar este Sitio Web. Cualquier término nuevo o diferente proporcionado por usted será específicamente rechazado por SOLICITUD DE EMPLEO. 
SOLICITUD DE EMPLEO podrá realizar cambios a éstos términos sin previo aviso.
20. Indemnización de SOLICITUD DE EMPLEO: Usted acepta defender, indemnizar y declarar exenta de responsabilidad a la Empresa y sus agentes asociados, sus funcionarios, directores, empleados y agentes, frente y contra cualquier reclamación, acción judicial o demanda, incluido sin limitaciones los daños, costos legales y contables derivados o resultantes de cualquier alegato resultado o en conexión con su uso del Sitio Web, de cualquier material publicado por usted o por cualquier incumplimiento a éstos términos. SOLICITUD DE EMPLEO le informará de la existencia de tales reclamaciones, demandas o procedimientos judiciales y le asistirá, a su costo, en la defensa de tales reclamaciones, demandas o procedimientos judiciales. 
21. Información del usuario: El Aviso de Privacidad de SOLICITUD DE EMPLEO incorpora este acuerdo.
22. Notificaciones y preguntas: Preguntas acerca del uso de este Sitio Web deberán ser dirigidas a ayuda@solicituddeempleo.com.mx , notificaciones deberán ser dirigidas a la dirección mostrada en el Sitio Web. 
23. Aviso de privacidad: Todos los usuarios debidamente registrados en solicituddeempleo.com.mx deberán aceptar el aviso de privacidad   te pedimos de favor leerlo cuidadosamente antes de tu inscripción. 